In [2]:
# 라이브러리 불러오기
import numpy as np

In [3]:
# Numpy 객체 정보를 확인하기 위한 사용자 함수 정의 : 객체타입, 구조, 차원, 데이터타입
def np_print(arr):
    text="""
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data : \n {}""".format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

## 산술연산 

- 더하기 : +, add()
- 빼기 : -, subtract()
- 나누기 :  / , divide()
- 곱하기 : *, multiply()
- 지수곱 표현 : exp()
- 제곱근 : sqrt()
- 로그 : log()
- 내적(행렬곱) : dot()

In [16]:
# 1부터 10미만의 범위(지정범위)에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열의 배열
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# 4이상 13미만의 범위에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열 배열 생성
b = np.arange(4, 13).reshape(3, 3)
b

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
# 10 ~ 21까지 3행 4열 형태로 만들기
c = np.arange(10, 22).reshape(3, 4)
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### 더하기
    - 배열 + 배열
    - np.add(arr1, arr2)

In [19]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(b)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# 산술연산자
a + b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [22]:
# np.add(배열1, 배열2)
np.add(a, b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [25]:
# 구조 다른 배열간의 산술연산자 사용시 : 특정 조건을 만족하지 않으면 에러가 납니다.
b + c # 구조가 되도록이면 안다르게 해야함

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### 빼기
    
    - 배열 - 배열
    - np.substract(arr1, arr2)

In [27]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
# 산술연산자
a - b

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [29]:
b - a

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
# 메서드 활용